services:
    web1:
        build: ./library_app
        container_name: task_app
        restart: always
        volumes:
          - ./library_app:/app
        ports:
          - "8001:8000"
        depends_on:
          - db
        env_file:
          - .env
        command: >
          sh -c "python manage.py makemigrations && 
          python manage.py migrate && 
          python manage.py runserver 0.0.0.0.:8000"